#
#	This file is part of the OrangeFox Recovery Project
# 	Copyright (C) 2018-2022 The OrangeFox Recovery Project
#	
#	OrangeFox is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	any later version.
#
#	OrangeFox is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
# 	This software is released under GPL version 3 or any later version.
#	See <http://www.gnu.org/licenses/>.
# 	
# 	Please maintain this if you use this script or any part of it
#

LOCAL_CFLAGS += -Wno-unused-parameter -Wno-unused-function -Wno-unused-variable -Wno-unused-result
#LOCAL_CFLAGS += -Wno-implicit-fallthrough -Wno-format-extra-args

ifneq ($(FOX_VERSION),)
    LOCAL_CFLAGS += -DFOX_VERSION='"$(FOX_VERSION)"'
else
    LOCAL_CFLAGS += -DFOX_VERSION='"Unofficial"'
endif

ifeq ($(FOX_VARIANT),)
    LOCAL_CFLAGS += -DFOX_VARIANT='"default"'
else
    LOCAL_CFLAGS += -DFOX_VARIANT='"$(FOX_VARIANT)"'
endif

DEVICE := $(subst omni_,,$(TARGET_PRODUCT))

ifeq ($(FOX_DEVICE_MODEL),)
    LOCAL_CFLAGS += -DFOX_DEVICE_MODEL='"$(DEVICE)"'
else
    LOCAL_CFLAGS += -DFOX_DEVICE_MODEL='"$(FOX_DEVICE_MODEL)"'
endif

# enable vbmeta patch in magiskboot 24+
ifeq ($(OF_PATCH_VBMETA_FLAG),1)
    LOCAL_CFLAGS += -DOF_PATCH_VBMETA_FLAG='"1"'
    export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
    export OF_USE_MAGISKBOOT=1
    $(warning Do not use "OF_PATCH_VBMETA_FLAG" unless you are sure that it is needed!)
endif

ifeq ($(AB_OTA_UPDATER),true)
    export OF_AB_DEVICE=1
endif

ifeq ($(OF_AB_DEVICE),1)
    LOCAL_CFLAGS += -DOF_USE_MAGISKBOOT_FOR_ALL_PATCHES='"1"'
    LOCAL_CFLAGS += -DOF_USE_MAGISKBOOT='"1"'
    LOCAL_CFLAGS += -DOF_AB_DEVICE='"1"'
    LOCAL_CFLAGS += -DAB_OTA_UPDATER=1
    export OF_AB_DEVICE=1
    export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
    export OF_USE_MAGISKBOOT=1
endif

ifeq ($(OF_VANILLA_BUILD),1)
    LOCAL_CFLAGS += -DOF_VANILLA_BUILD='"1"'
    LOCAL_CFLAGS += -DOF_SKIP_ORANGEFOX_PROCESS='"1"'
    LOCAL_CFLAGS += -DOF_DISABLE_MIUI_SPECIFIC_FEATURES='"1"'
    LOCAL_CFLAGS += -DOF_DONT_PATCH_ON_FRESH_INSTALLATION='"1"'
    LOCAL_CFLAGS += -DOF_DONT_PATCH_ENCRYPTED_DEVICE='"1"'
    LOCAL_CFLAGS += -DOF_KEEP_DM_VERITY_FORCED_ENCRYPTION='"1"'
    export OF_VANILLA_BUILD=1
    OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
    OF_TWRP_COMPATIBILITY_MODE := 1
endif

ifeq ($(OF_DISABLE_MIUI_SPECIFIC_FEATURES),1)
    LOCAL_CFLAGS += -DOF_DISABLE_MIUI_SPECIFIC_FEATURES='"1"'
    OF_TWRP_COMPATIBILITY_MODE := 1
endif

ifeq ($(OF_DISABLE_MIUI_OTA_BY_DEFAULT),1)
    LOCAL_CFLAGS += -DOF_DISABLE_MIUI_OTA_BY_DEFAULT='"1"'
endif

ifeq ($(OF_TWRP_COMPATIBILITY_MODE),1)
    LOCAL_CFLAGS += -DOF_TWRP_COMPATIBILITY_MODE='"1"'
    OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
endif

# check for conflicts
ifeq ($(OF_SUPPORT_ALL_BLOCK_OTA_UPDATES),1)
   ifeq ($(OF_DISABLE_MIUI_SPECIFIC_FEATURES),1)
        $(warning You cannot use "OF_SUPPORT_ALL_BLOCK_OTA_UPDATES" with "OF_DISABLE_MIUI_SPECIFIC_FEATURES"/"OF_TWRP_COMPATIBILITY_MODE")
        $(error Fix your build vars! Exiting)
   endif
endif
#

ifeq ($(OF_SKIP_ORANGEFOX_PROCESS),1)
    LOCAL_CFLAGS += -DOF_SKIP_ORANGEFOX_PROCESS='"1"'
    LOCAL_CFLAGS += -DOF_DONT_PATCH_ON_FRESH_INSTALLATION='"1"'
    export OF_DONT_PATCH_ON_FRESH_INSTALLATION=1
endif

ifeq ($(OF_DONT_PATCH_ON_FRESH_INSTALLATION),1)
    LOCAL_CFLAGS += -DOF_DONT_PATCH_ON_FRESH_INSTALLATION='"1"'
endif

ifneq ($(FOX_BUILD_TYPE),)
    LOCAL_CFLAGS += -DFOX_BUILD_TYPE='"$(FOX_BUILD_TYPE)"'
else
    LOCAL_CFLAGS += -DFOX_BUILD_TYPE='"Unofficial"'
endif

ifeq ($(OF_FORCE_DISABLE_DM_VERITY_MIUI),1)
    LOCAL_CFLAGS += -DOF_FORCE_DISABLE_DM_VERITY_MIUI='"1"'
    export OF_FORCE_MAGISKBOOT_BOOT_PATCH_MIUI=1
endif

ifeq ($(OF_FORCE_MAGISKBOOT_BOOT_PATCH_MIUI),1)
    LOCAL_CFLAGS += -DOF_FORCE_MAGISKBOOT_BOOT_PATCH_MIUI='"1"'
    export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
    export OF_USE_MAGISKBOOT=1
endif

# LZMA
ifeq ($(FOX_USE_LZMA_COMPRESSION),1)
    ifeq ($(LZMA_RAMDISK_TARGETS),)
    	LZMA_RAMDISK_TARGETS := recovery
    endif
    export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
    export OF_USE_MAGISKBOOT=1
endif

ifeq ($(OF_USE_MAGISKBOOT),1)
    LOCAL_CFLAGS += -DOF_USE_MAGISKBOOT='"1"'
endif

ifeq ($(OF_USE_MAGISKBOOT_FOR_ALL_PATCHES),1)
    LOCAL_CFLAGS += -DOF_USE_MAGISKBOOT_FOR_ALL_PATCHES='"1"'
    LOCAL_CFLAGS += -DOF_USE_MAGISKBOOT='"1"'
    export OF_USE_MAGISKBOOT=1
endif

ifeq ($(OF_NO_MIUI_PATCH_WARNING),1)
    LOCAL_CFLAGS += -DOF_NO_MIUI_PATCH_WARNING='"1"'
endif

ifeq ($(OF_DONT_PATCH_ENCRYPTED_DEVICE),1)
    LOCAL_CFLAGS += -DOF_DONT_PATCH_ENCRYPTED_DEVICE='"1"'
endif

ifneq ($(OF_MAINTAINER),)
    LOCAL_CFLAGS += -DOF_MAINTAINER='"$(OF_MAINTAINER)"'
else
    LOCAL_CFLAGS += -DOF_MAINTAINER='"Unofficial"'
endif

ifneq ($(OF_FLASHLIGHT_ENABLE),)
    LOCAL_CFLAGS += -DOF_FLASHLIGHT_ENABLE='"$(OF_FLASHLIGHT_ENABLE)"'
else
    LOCAL_CFLAGS += -DOF_FLASHLIGHT_ENABLE='"1"'
endif

ifneq ($(OF_SPLASH_MAX_SIZE),)
    LOCAL_CFLAGS += -DOF_SPLASH_MAX_SIZE='"$(OF_SPLASH_MAX_SIZE)"'
else
    LOCAL_CFLAGS += -DOF_SPLASH_MAX_SIZE='"4096"'
endif

ifneq ($(FOX_ADVANCED_SECURITY),)
    LOCAL_CFLAGS += -DFOX_ADVANCED_SECURITY='"$(FOX_ADVANCED_SECURITY)"'
endif

ifeq ($(OF_DEVICE_WITHOUT_PERSIST),1)
    LOCAL_CFLAGS += -DOF_DEVICE_WITHOUT_PERSIST='"1"'
endif

ifneq ($(FOX_CURRENT_DEV_STR),)
    LOCAL_CFLAGS += -DFOX_CURRENT_DEV_STR='"$(FOX_CURRENT_DEV_STR)"'
else
    LOCAL_CFLAGS += -DFOX_CURRENT_DEV_STR='"latest"'
endif

ifeq ($(FOX_OLD_DECRYPT_RELOAD),1)
    LOCAL_CFLAGS += -DFOX_OLD_DECRYPT_RELOAD='"1"'
endif

ifeq ($(FOX_USE_NANO_EDITOR), 1)
    export FOX_USE_NANO_EDITOR=1
    LOCAL_CFLAGS += -DFOX_USE_NANO_EDITOR='"1"'
endif

ifneq ($(OF_SCREEN_H),)
    LOCAL_CFLAGS += -DOF_SCREEN_H='"$(OF_SCREEN_H)"'
else
    LOCAL_CFLAGS += -DOF_SCREEN_H='"1920"'
endif

ifneq ($(OF_STATUS_H),)
    LOCAL_CFLAGS += -DOF_STATUS_H='"$(OF_STATUS_H)"'
else
    LOCAL_CFLAGS += -DOF_STATUS_H='"72"'
endif

ifneq ($(OF_HIDE_NOTCH),)
    LOCAL_CFLAGS += -DOF_HIDE_NOTCH='"$(OF_HIDE_NOTCH)"'
else
    LOCAL_CFLAGS += -DOF_HIDE_NOTCH='"0"'
endif

ifneq ($(OF_STATUS_INDENT_LEFT),)
    LOCAL_CFLAGS += -DOF_STATUS_INDENT_LEFT='"$(OF_STATUS_INDENT_LEFT)"'
else
    LOCAL_CFLAGS += -DOF_STATUS_INDENT_LEFT='"20"'
endif

ifneq ($(OF_STATUS_INDENT_RIGHT),)
    LOCAL_CFLAGS += -DOF_STATUS_INDENT_RIGHT='"$(OF_STATUS_INDENT_RIGHT)"'
else
    LOCAL_CFLAGS += -DOF_STATUS_INDENT_RIGHT='"20"'
endif

ifneq ($(OF_CLOCK_POS),)
    LOCAL_CFLAGS += -DOF_CLOCK_POS='"$(OF_CLOCK_POS)"'
else
    LOCAL_CFLAGS += -DOF_CLOCK_POS='"0"'
endif

ifneq ($(OF_ALLOW_DISABLE_NAVBAR),)
    LOCAL_CFLAGS += -DOF_ALLOW_DISABLE_NAVBAR='"$(OF_ALLOW_DISABLE_NAVBAR)"'
else
    LOCAL_CFLAGS += -DOF_ALLOW_DISABLE_NAVBAR='"1"'
endif

ifneq ($(OF_FL_PATH1),)
    LOCAL_CFLAGS += -DOF_FL_PATH1='"$(OF_FL_PATH1)"'
else
    LOCAL_CFLAGS += -DOF_FL_PATH1='""'
endif

ifneq ($(OF_FL_PATH2),)
    LOCAL_CFLAGS += -DOF_FL_PATH2='"$(OF_FL_PATH2)"'
else
    LOCAL_CFLAGS += -DOF_FL_PATH2='""'
endif

ifeq ($(OF_USE_HEXDUMP),1)
    LOCAL_CFLAGS += -DOF_USE_HEXDUMP='"1"'
endif

ifeq ($(OF_SKIP_FBE_DECRYPTION),1)
    LOCAL_CFLAGS += -DOF_SKIP_FBE_DECRYPTION='"1"'
endif

ifneq ($(OF_SKIP_FBE_DECRYPTION_SDKVERSION),)
    LOCAL_CFLAGS += -DOF_SKIP_FBE_DECRYPTION_SDKVERSION='"$(OF_SKIP_FBE_DECRYPTION_SDKVERSION)"'
endif

ifeq ($(OF_CLASSIC_LEDS_FUNCTION),1)
    LOCAL_CFLAGS += -DOF_CLASSIC_LEDS_FUNCTION='"1"'
endif

ifeq ($(OF_KEEP_DM_VERITY_FORCED_ENCRYPTION),1)
    LOCAL_CFLAGS += -DOF_KEEP_DM_VERITY_FORCED_ENCRYPTION='"1"'
    OF_KEEP_DM_VERITY := 1
    OF_KEEP_FORCED_ENCRYPTION := 1
endif

ifneq ($(OF_TARGET_DEVICES),)
    LOCAL_CFLAGS += -DOF_TARGET_DEVICES='"$(OF_TARGET_DEVICES)"'
endif

ifneq ($(OF_CUSTOM_BACKUP_EXCLUSIONS),)
    LOCAL_CFLAGS += -DOF_CUSTOM_BACKUP_EXCLUSIONS='"$(OF_CUSTOM_BACKUP_EXCLUSIONS)"'
endif

ifeq ($(OF_KEEP_DM_VERITY),1)
    LOCAL_CFLAGS += -DOF_KEEP_DM_VERITY='"1"'
endif

ifeq ($(OF_KEEP_FORCED_ENCRYPTION),1)
    LOCAL_CFLAGS += -DOF_KEEP_FORCED_ENCRYPTION='"1"'
endif

ifeq ($(OF_DISABLE_DM_VERITY_FORCED_ENCRYPTION),1)
    LOCAL_CFLAGS += -DOF_DISABLE_DM_VERITY_FORCED_ENCRYPTION='"1"'
    OF_DISABLE_DM_VERITY := 1
    OF_DISABLE_FORCED_ENCRYPTION := 1
endif

ifeq ($(OF_DISABLE_DM_VERITY),1)
    LOCAL_CFLAGS += -DOF_DISABLE_DM_VERITY='"1"'
endif

ifeq ($(OF_DISABLE_FORCED_ENCRYPTION),1)
    LOCAL_CFLAGS += -DOF_DISABLE_FORCED_ENCRYPTION='"1"'
endif

ifeq ($(OF_FORCE_DISABLE_DM_VERITY_FORCED_ENCRYPTION),1)
    LOCAL_CFLAGS += -DOF_FORCE_DISABLE_DM_VERITY_FORCED_ENCRYPTION='"1"'
    OF_FORCE_DISABLE_DM_VERITY := 1
    OF_FORCE_DISABLE_FORCED_ENCRYPTION := 1
endif

ifeq ($(OF_FORCE_DISABLE_DM_VERITY),1)
    LOCAL_CFLAGS += -DOF_FORCE_DISABLE_DM_VERITY='"1"'
endif

ifeq ($(OF_FORCE_DISABLE_FORCED_ENCRYPTION),1)
    LOCAL_CFLAGS += -DOF_FORCE_DISABLE_FORCED_ENCRYPTION='"1"'
endif

ifeq ($(OF_CHECK_OVERWRITE_ATTEMPTS),1)
    LOCAL_CFLAGS += -DOF_CHECK_OVERWRITE_ATTEMPTS='"1"'
endif

ifeq ($(FOX_ENABLE_LAB),1)
    export FOX_ENABLE_LAB=1
    LOCAL_CFLAGS += -DFOX_ENABLE_LAB='"1"'
endif

ifeq ($(OF_NO_MIUI_OTA_VENDOR_BACKUP),1)
    LOCAL_CFLAGS += -DOF_NO_MIUI_OTA_VENDOR_BACKUP='"1"'
endif

ifeq ($(OF_REDUCE_DECRYPTION_TIMEOUT),1)
    LOCAL_CFLAGS += -DOF_REDUCE_DECRYPTION_TIMEOUT='"1"'
endif

ifeq ($(OF_DONT_KEEP_LOG_HISTORY),1)
    LOCAL_CFLAGS += -DOF_DONT_KEEP_LOG_HISTORY='"1"'
endif

ifeq ($(OF_SUPPORT_ALL_BLOCK_OTA_UPDATES),1)
    LOCAL_CFLAGS += -DOF_SUPPORT_ALL_BLOCK_OTA_UPDATES='"1"'
endif

ifeq ($(OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR),1)
    LOCAL_CFLAGS += -DOF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR='"1"'
endif

ifeq ($(OF_OTA_BACKUP_STOCK_BOOT_IMAGE),1)
    LOCAL_CFLAGS += -DOF_OTA_BACKUP_STOCK_BOOT_IMAGE
endif

ifeq ($(OF_FBE_METADATA_MOUNT_IGNORE),1)
    LOCAL_CFLAGS += -DOF_FBE_METADATA_MOUNT_IGNORE='"1"'
endif

ifeq ($(OF_USE_SYSTEM_FINGERPRINT),1)
    LOCAL_CFLAGS += -DOF_USE_SYSTEM_FINGERPRINT='"1"'
endif

ifeq ($(OF_PATCH_AVB20),1)
    LOCAL_CFLAGS += -DOF_PATCH_AVB20='"1"'
endif

#ifeq ($(OF_SKIP_MULTIUSER_FOLDERS_BACKUP),1)
#    LOCAL_CFLAGS += -DOF_SKIP_MULTIUSER_FOLDERS_BACKUP='"1"'
#endif

ifeq ($(OF_USE_TWRP_SAR_DETECT),1)
    LOCAL_CFLAGS += -DOF_USE_TWRP_SAR_DETECT='"1"'
endif

ifneq ($(OF_QUICK_BACKUP_LIST),)
    LOCAL_CFLAGS += -DOF_QUICK_BACKUP_LIST='"$(OF_QUICK_BACKUP_LIST)"'
endif

ifeq ($(OF_USE_LOCKSCREEN_BUTTON),1)
    LOCAL_CFLAGS += -DOF_USE_LOCKSCREEN_BUTTON
endif

# disable by default the USB storage button on the "Mount" menu
ifneq ($(OF_ENABLE_USB_STORAGE),1)
    TW_NO_USB_STORAGE := true
endif

# post-format
ifeq ($(OF_FORCE_CREATE_DATA_MEDIA_ON_FORMAT),1)
   OF_RUN_POST_FORMAT_PROCESS := 1
   LOCAL_CFLAGS += -DOF_FORCE_CREATE_DATA_MEDIA_ON_FORMAT='"1"'
endif

ifeq ($(OF_RUN_POST_FORMAT_PROCESS),1)
    $(warning "OF_RUN_POST_FORMAT_PROCESS" is deprecated. It causes issues with Android 11+ encryption of the internal storage)
    LOCAL_CFLAGS += -DOF_RUN_POST_FORMAT_PROCESS='"1"'
endif

# process these here instead of OrangeFox.sh
ifeq ($(OF_DISABLE_EXTRA_ABOUT_PAGE),1)
    LOCAL_CFLAGS += -DOF_DISABLE_EXTRA_ABOUT_PAGE=1
endif

ifeq ($(FOX_ENABLE_APP_MANAGER),1)
    LOCAL_CFLAGS += -DFOX_ENABLE_APP_MANAGER='"1"'
endif

ifeq ($(OF_NO_SPLASH_CHANGE),1)
    LOCAL_CFLAGS += -DOF_NO_SPLASH_CHANGE='"1"'
endif

ifeq ($(FOX_DELETE_MAGISK_ADDON),1)
    LOCAL_CFLAGS += -DFOX_DELETE_MAGISK_ADDON='"1"'
endif

ifeq ($(OF_USE_GREEN_LED),0)
    LOCAL_CFLAGS += -DOF_USE_GREEN_LED='"0"'
endif

ifeq ($(OF_NO_TREBLE_COMPATIBILITY_CHECK),1)
    LOCAL_CFLAGS += -DOF_NO_TREBLE_COMPATIBILITY_CHECK='"1"'
endif

ifeq ($(OF_USE_LEGACY_CRYPTO),1)
   export OF_USE_LEGACY_CRYPTO=1
   LOCAL_CFLAGS += -DOF_USE_LEGACY_CRYPTO='"1"'
endif

ifeq ($(OF_LEGACY_SHAR512),1)
    LOCAL_CFLAGS += -DOF_LEGACY_SHAR512=1
endif

ifneq ($(TW_OZIP_DECRYPT_KEY),)
    OF_SUPPORT_OZIP_DECRYPTION := 1
endif

# from gui/Android.mk
ifeq ($(OF_SUPPORT_OZIP_DECRYPTION),1)
    LOCAL_CFLAGS += -DOF_SUPPORT_OZIP_DECRYPTION='"1"'
ifneq ($(TW_OZIP_DECRYPT_KEY),)
    LOCAL_CFLAGS += -DTW_OZIP_DECRYPT_KEY=\"$(TW_OZIP_DECRYPT_KEY)\"
else
    LOCAL_CFLAGS += -DTW_OZIP_DECRYPT_KEY=0
endif
endif

# adopted storage
ifeq ($(OF_SKIP_DECRYPTED_ADOPTED_STORAGE),1)
    LOCAL_CFLAGS += -DOF_SKIP_DECRYPTED_ADOPTED_STORAGE='"1"'
endif

# unblock block partitions before flashinh
ifeq ($(OF_UNLOCK_BLOCK_PARTITIONS),1)
    LOCAL_CFLAGS += -DOF_UNLOCK_BLOCK_PARTITIONS='"1"'
endif
#
